# Generated by Django 3.0.4 on 2020-03-31 23:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import pythonspain.core.files


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsignmentImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        upload_to=pythonspain.core.files.UploadToDir(
                            "imports", random_name=False
                        ),
                        verbose_name="data",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Idle"),
                            (1, "Running"),
                            (2, "Finished"),
                            (3, "Error"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "items",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="items"
                    ),
                ),
            ],
            options={
                "verbose_name": "Consignment import",
                "verbose_name_plural": "Consignment imports",
                "ordering": ["-created"],
            },
        )
    ]
