# Generated by Django 3.0.4 on 2020-03-29 20:39

from django.db import migrations, models
import pythonspain.core.files


class Migration(migrations.Migration):

    dependencies = [("banks", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="consignmentimport",
            name="data",
            field=models.FileField(
                upload_to=pythonspain.core.files.UploadToDir(
                    "imports", random_name=False
                )
            ),
        ),
        migrations.AlterField(
            model_name="consignmentimport",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Idle"), (1, "Running"), (2, "Finished"), (3, "Error")],
                default=0,
            ),
        ),
    ]
