# Generated by Django 3.0.4 on 2020-03-29 20:55

from django.db import migrations, models
import pythonspain.core.files


class Migration(migrations.Migration):

    dependencies = [("banks", "0002_auto_20200329_2039")]

    operations = [
        migrations.AlterModelOptions(
            name="consignmentimport",
            options={
                "ordering": ["-created"],
                "verbose_name": "Consignment import",
                "verbose_name_plural": "Consignment imports",
            },
        ),
        migrations.AlterField(
            model_name="consignmentimport",
            name="data",
            field=models.FileField(
                upload_to=pythonspain.core.files.UploadToDir(
                    "imports", random_name=False
                ),
                verbose_name="data",
            ),
        ),
        migrations.AlterField(
            model_name="consignmentimport",
            name="items",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="items"
            ),
        ),
        migrations.AlterField(
            model_name="consignmentimport",
            name="status",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "Idle"), (1, "Running"), (2, "Finished"), (3, "Error")],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
