# Generated by Django 3.0.4 on 2020-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("partners", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=75, null=True, verbose_name="email"),
        )
    ]
