# Generated by Django 3.0.4 on 2020-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("partners", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="charge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "President"),
                    ("vicepresident", "Vice president"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("vocal", "Vocal"),
                ],
                max_length=16,
                null=True,
                verbose_name="charge",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="has_board_directors_charge",
            field=models.BooleanField(
                default=False, verbose_name="has board directors charge"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="nif",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NIF"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="number",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="number"
            ),
        ),
    ]
