# Generated by Django 3.0.4 on 2020-04-02 17:06

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import pythonspain.core.files


class Migration(migrations.Migration):

    dependencies = [("partners", "0002_member_email")]

    operations = [
        migrations.CreateModel(
            name="MemberExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pythonspain.core.files.UploadToDir(
                            "exports", random_name=True
                        ),
                        verbose_name="data",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Idle"),
                            (1, "Running"),
                            (2, "Finished"),
                            (3, "Error"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "items",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="items"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PartnerExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pythonspain.core.files.UploadToDir(
                            "exports", random_name=True
                        ),
                        verbose_name="data",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Idle"),
                            (1, "Running"),
                            (2, "Finished"),
                            (3, "Error"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "items",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="items"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
