# Generated by Django 3.0.4 on 2020-03-29 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("partners", "0002_auto_20200329_1640")]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime.today, null=True
            ),
        )
    ]
