# Generated by Django 3.0.4 on 2020-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("partners", "0003_notice_date")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="comment"),
        )
    ]
