# Generated by Django 3.0.4 on 2020-04-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("partners", "0003_memberexport_partnerexport")]

    operations = [
        migrations.AlterModelOptions(
            name="memberexport",
            options={
                "ordering": ["-created"],
                "verbose_name": "Members export",
                "verbose_name_plural": "Members exports",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerexport",
            options={
                "ordering": ["-created"],
                "verbose_name": "Partners export",
                "verbose_name_plural": "Partners exports",
            },
        ),
    ]
