# Generated by Django 3.0.4 on 2020-04-02 17:17

from django.db import migrations, models

import pythonspain.core.files


class Migration(migrations.Migration):

    dependencies = [("partners", "0004_auto_20200402_1715")]

    operations = [
        migrations.AlterField(
            model_name="memberexport",
            name="data",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pythonspain.core.files.UploadToDir(
                    "exports", random_name=False
                ),
                verbose_name="data",
            ),
        ),
        migrations.AlterField(
            model_name="partnerexport",
            name="data",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pythonspain.core.files.UploadToDir(
                    "exports", random_name=False
                ),
                verbose_name="data",
            ),
        ),
    ]
