# Generated by Django 3.0.4 on 2020-03-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("partners", "0004_auto_20200329_1734")]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "ordering": ["-number"],
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        )
    ]
