# Generated by Django 3.0.4 on 2020-03-29 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("partners", "0005_auto_20200329_1757")]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.today,
                null=True,
                verbose_name="date",
            ),
        ),
    ]
