# Generated by Django 3.0.4 on 2020-03-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("partners", "0006_auto_20200329_1800")]

    operations = [
        migrations.AlterModelOptions(
            name="fee",
            options={
                "ordering": ["-date"],
                "verbose_name": "Fee",
                "verbose_name_plural": "Fees",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["-created"],
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
    ]
