# Generated by Django 3.1.1 on 2020-11-29 19:54

from django.db import migrations, models
import functools
import pythonspain.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20200627_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='allow_notifications',
            field=models.BooleanField(default=True, verbose_name='allow sent notificacions'),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_payment_doc',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(pythonspain.partners.models.partner_files_directory_path, *('first_payment_doc',), **{}), verbose_name='first payment document'),
        ),
        migrations.AddField(
            model_name='partner',
            name='identity_doc',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(pythonspain.partners.models.partner_files_directory_path, *('identity_doc',), **{}), verbose_name='identity document'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_rgpd_consent',
            field=models.BooleanField(default=True, verbose_name='is RGDP consent'),
        ),
    ]
