#!/bin/sh

set -o errexit
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput
python /app/manage.py compilemessages
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
