# Generated by Django 3.0.4 on 2020-03-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("date_joined",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        )
    ]
