# Generated by Django 3.0.4 on 2020-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20200329_1003")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates if the user has the email verified.",
                verbose_name="verified",
            ),
        )
    ]
